version: "3"
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGODB_URI: "mongodb://mongodb:27017/ip-address-app"
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - redis

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis
    ports:
      - 6379:6379
